// quiz_model.dart
import 'package:cloud_firestore/cloud_firestore.dart';

class QuizModel {
  final String id;
  final String title;
  final String description;
  final String category;
  final String quizType; // "exercise" | "exam"
  final int duration; // minutes
  final DateTime deadline;
  final int numQuestions;
  final String image; // asset image path
  final String createdBy;
  final DateTime createdAt;
  final List<QuestionModel> questions;
  final int maxAttempts; // new: limit attempts (optional, default 1)

  QuizModel({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.quizType,
    required this.duration,
    required this.deadline,
    required this.numQuestions,
    required this.image,
    required this.createdBy,
    required this.createdAt,
    required this.questions,
    required this.maxAttempts,
  });

  factory QuizModel.fromDocument(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>? ?? {};

    final deadlineField = data['deadline'];
    DateTime parsedDeadline;
    if (deadlineField is Timestamp) parsedDeadline = deadlineField.toDate();
    else if (deadlineField is DateTime) parsedDeadline = deadlineField;
    else parsedDeadline = DateTime.now();

    final createdAtField = data['createdAt'];
    DateTime parsedCreatedAt;
    if (createdAtField is Timestamp) parsedCreatedAt = createdAtField.toDate();
    else if (createdAtField is DateTime) parsedCreatedAt = createdAtField;
    else parsedCreatedAt = DateTime.now();

    final rawQuestions = data['questions'] as List<dynamic>? ?? [];

    return QuizModel(
      id: doc.id, // Successfully getting the Quiz ID
      title: data['title'] ?? '',
      description: data['description'] ?? '',
      category: data['category'] ?? '',
      quizType: data['quizType'] ?? data['difficulty'] ?? 'exercise',
      duration: (data['duration'] is num) ? (data['duration'] as num).toInt() : 0,
      deadline: parsedDeadline,
      numQuestions: (data['numQuestions'] is num) ? (data['numQuestions'] as num).toInt() : rawQuestions.length,
      image: data['image'] ?? '',
      createdBy: data['createdBy'] ?? '',
      createdAt: parsedCreatedAt,
      // ⭐ CRITICAL FIX: Assign a unique ID to each question based on Quiz ID and index
      questions: rawQuestions.asMap().entries.map((entry) {
        final index = entry.key;
        final q = entry.value;

        QuestionModel questionModel;
        if (q is Map<String, dynamic>) {
          questionModel = QuestionModel.fromMap(q);
        } else if (q is Map) {
          questionModel = QuestionModel.fromMap(Map<String, dynamic>.from(q));
        } else {
          questionModel = QuestionModel(type: 'objective', question: '', options: [], answer: 0);
        }
        
        // Re-create the model with the generated unique ID
        return QuestionModel(
          id: questionModel.id ?? '${doc.id}_q$index', // Use QuizID_qIndex as the ID
          type: questionModel.type,
          question: questionModel.question,
          options: questionModel.options,
          answer: questionModel.answer,
          expectedAnswer: questionModel.expectedAnswer,
          aiEvaluated: questionModel.aiEvaluated,
        );
      }).toList(),
      maxAttempts: (data['maxAttempts'] is num) ? (data['maxAttempts'] as num).toInt() : 1,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'description': description,
      'category': category,
      'quizType': quizType,
      'duration': duration,
      'deadline': Timestamp.fromDate(deadline),
      'numQuestions': numQuestions,
      'image': image,
      'createdBy': createdBy,
      'createdAt': Timestamp.fromDate(createdAt),
      'questions': questions.map((q) => q.toMap()).toList(),
      'maxAttempts': maxAttempts,
    };
  }
}

class QuestionModel {
  // ⭐ NEW ID FIELD ADDED HERE
  final String? id; // Unique ID (generated by QuizModel.fromDocument if not in map)
  final String type; // "objective" | "subjective"
  final String question;
  final List<String>? options; // objective only
  final int? answer; // objective only (index)
  final String? expectedAnswer; // subjective only
  final bool? aiEvaluated; // subjective only

  QuestionModel({
    this.id, // Make it optional in the constructor
    required this.type,
    required this.question,
    this.options,
    this.answer,
    this.expectedAnswer,
    this.aiEvaluated,
  });

  factory QuestionModel.fromMap(Map<String, dynamic> map) {
    return QuestionModel(
      id: map['id'], // Map the ID if it exists in the data source
      type: map['type'] ?? 'objective',
      question: map['question'] ?? '',
      options: map['options'] != null ? List<String>.from(map['options']) : null,
      answer: map['answer'] != null ? (map['answer'] is num ? (map['answer'] as num).toInt() : null) : null,
      expectedAnswer: map['expectedAnswer'],
      aiEvaluated: map['aiEvaluated'] ?? false,
    );
  }

  Map<String, dynamic> toMap() {
    final map = <String, dynamic>{
      'type': type, 
      'question': question
    };
    if (id != null) map['id'] = id; // Map the ID back out
    
    if (type == 'objective') {
      map['options'] = options ?? [];
      if (answer != null) map['answer'] = answer;
    } else {
      map['expectedAnswer'] = expectedAnswer ?? '';
      map['aiEvaluated'] = aiEvaluated ?? false;
    }
    return map;
  }
}