// dashboard.dart

//import 'package:cscore/AIModule/ai_chatbox.dart';
//import 'package:cscore/ForumModule/forum.dart';
//import 'package:cscore/LearningModule/learning.dart';
import 'package:cscore/ProgressTrackerModule/progress.dart';
//import 'package:cscore/QuizModule/quiz.dart';
import 'package:cscore/AccountModule/user_profile.dart';

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cscore/firebase_options.dart'; // generated by flutterfire configure
import 'package:cscore/dashboardModule/screens/teacher_dashboard.dart';
import 'package:cscore/dashboardModule/screens/student_dashboard.dart';

class Dashboard extends StatefulWidget {
  const Dashboard({super.key});

  @override
  State<Dashboard> createState() => _DashboardState();
}

class _DashboardState extends State<Dashboard> {
  bool _firebaseInitialized = false;

  @override
  void initState() {
    super.initState();
    _initFirebase();
  }

  // 🔹 Initialize Firebase once
  Future<void> _initFirebase() async {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    setState(() => _firebaseInitialized = true);
  }

  @override
  Widget build(BuildContext context) {
    // Show a loading spinner until Firebase is ready
    if (!_firebaseInitialized) {
      return const Scaffold(
        body: Center(child: CircularProgressIndicator()),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('CScore+'),
        backgroundColor: Colors.grey[200],
      ),
<<<<<<< Updated upstream
      
      body: Padding(padding: EdgeInsetsGeometry.all(10),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Center(
              child: Text('Welcome to CScore+',style: TextStyle(fontSize: 20),),
            ),
            Divider(
              height: 60,
              color: Colors.grey[800],
            ),
            
            Text(
              'Learning Modules',
              style: TextStyle(
                color: Colors.blue,
                letterSpacing: 2.0,
              
              ),
            ),
            SizedBox(height:10),
            Row(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                Container(color: Colors.green[200],child: Text('HTML'),width: 100, height: 100,),
                SizedBox(width:10),
                Container(color: Colors.amber[200],child: Text('CSS'),width: 100, height: 100,),
              ],
            ),


            TextButton(
              onPressed: (){
                Navigator.pushNamed(context, '/learning');
              }, 
              child: Text('Go to Learning Module'),
              ),
             Divider(
              height: 60,
              color: Colors.grey[800],
            ),
            
            Text(
              'Quizzes and Assessment',
              style: TextStyle(
                color: Colors.blue,
                letterSpacing: 2.0,
              
              ),
            ),
            SizedBox(height:10),
            Row(
              children: [
                Container(color: Colors.green[200],child: Text('HTML'),width: 100, height: 100,),
                SizedBox(width:10),
                Container(color: Colors.amber[200],child: Text('CSS'),width: 100, height: 100,),
              ],
            ),
            TextButton(
              onPressed: (){
                Navigator.pushNamed(context, '/quiz');
              }, 
              child: Text('Go to Quizzes and Assessment'),
              ),
              
            
        ],
      ),),
      
      floatingActionButton: FloatingActionButton(
            backgroundColor: Colors.grey[200],
            shape: const CircleBorder(),
            child: Text('AI CHAT', style: TextStyle(color: Colors.grey[800]),),
            onPressed: () {
              Navigator.pushNamed(context, '/ai');
            },
        ),
      
      
      bottomNavigationBar: BottomNavigationBar(
            type: BottomNavigationBarType.fixed,
            currentIndex: 1,
            selectedItemColor: Colors.blue,
            unselectedItemColor: Colors.black,
            onTap: (index){
              if(index == 0){
                Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const ProgressTracker()),);
              }
              else if(index == 2){
                Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const UserProfile()),);
              }

            },
            items: const[
                BottomNavigationBarItem(
                    
                    icon: Icon(Icons.track_changes),
                    label: '', 
                    
                ),
                BottomNavigationBarItem(
      
                    icon: Icon(Icons.home),
                    label: '', 
                ),
                BottomNavigationBarItem(
                    
                    icon: Icon(Icons.person),
                    label: '',
                ),
                
            ],
=======

      // 🔹 Dashboard Page Body
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Dashboard',
              style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 12),
            const Text(
              'Select your role to access the dashboard features:',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 28),

            // 🔹 Role Selector Buttons
            Center(
              child: Column(
                children: [
                  ElevatedButton.icon(
                    icon: const Icon(Icons.school),
                    label: const Text('Teacher Dashboard'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.blueGrey[700],
                      foregroundColor: Colors.white,
                      minimumSize: const Size(230, 55),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (_) => const TeacherDashboard()),
                      );
                    },
                  ),
                  const SizedBox(height: 16),
                  OutlinedButton.icon(
                    icon: const Icon(Icons.person),
                    label: const Text('Student Dashboard'),
                    style: OutlinedButton.styleFrom(
                      minimumSize: const Size(230, 55),
                      side: const BorderSide(color: Colors.blueGrey),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(builder: (_) => const StudentDashboard()),
                      );
                    },
                  ),
                ],
              ),
            ),

            const SizedBox(height: 40),
            const Divider(),
            const SizedBox(height: 16),
            const Text(
              'Overview',
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.w600),
            ),
            const SizedBox(height: 8),
            const Text(
              'This dashboard connects to Teacher and Student modules via Firebase. '
              'You can still access Learning, Quiz, Forum, and Profile via the bottom navigation bar below.',
              style: TextStyle(color: Colors.black87),
            ),
          ],
>>>>>>> Stashed changes
        ),
      ),

      // 🔹 Floating AI Chat Button
      floatingActionButton: FloatingActionButton(
        backgroundColor: Colors.grey[200],
        shape: const CircleBorder(),
        child: Text(
          'AI CHAT',
          style: TextStyle(color: Colors.grey[800]),
        ),
        onPressed: () {
          Navigator.pushNamed(context, '/ai');
        },
      ),

      // 🔹 Bottom Navigation Bar
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        currentIndex: 0,
        selectedItemColor: Colors.blue,
        unselectedItemColor: Colors.black,
        onTap: (index) {
          if (index == 1) {
            Navigator.pushReplacement(
              context,
              MaterialPageRoute(builder: (context) => const Learning()),
            );
          } else if (index == 2) {
            Navigator.pushReplacement(
              context,
              MaterialPageRoute(builder: (context) => const Quiz()),
            );
          } else if (index == 3) {
            Navigator.pushReplacement(
              context,
              MaterialPageRoute(builder: (context) => const Forum()),
            );
          } else if (index == 4) {
            Navigator.pushReplacement(
              context,
              MaterialPageRoute(builder: (context) => const UserProfile()),
            );
          }
        },
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            label: '',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.school),
            label: '',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.lightbulb_circle_outlined),
            label: '',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.forum),
            label: '',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.person),
            label: '',
          ),
        ],
      ),
    );
  }
}
